language: java
jdk:
- oraclejdk8
env:
  global:
  - SONATYPE_USERNAME=OzWolf
  - secure: VFWko4Bwwegmcb3krloK169xRqvXs3O9VAAk+SqZqGn7lDIUDNujrhguYbKF3+MYhywDcKZ4mNB9i4eKzjoeiUiwf1mfinUT+0Tr57KqojXHM2yH4HrxK8bqzgu24oPYPWnTqVZnBpZoIyZAbbcaRcCtm0Ir4TsgHc2/rJGuipU=
  - secure: OJofjkAn73LJephLssj5/f6t0xCxg2Hy7Hid0KL/kabM7II666B6Gp8uIfIHNB6WaSWmunCfboCU1W1eEEQVzx3ypRXiYOpf78MZ+sk3EGnwqToD6kKjUNoqXHNXFeXE/J7MXSfgQa90d6xXf8hBTNkoMpOWc1eHA3k6UKWDjZA=

script: mvn clean source:jar deploy --settings travis-settings.xml -Dgpg.passphrase=${GPG_PASSPHRASE}
notifications:
  email:
  - ozwolf@gmail.com
